'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
type M={id:string;home:string;away:string;league:string;scoreHome:number;scoreAway:number;live:boolean;finished:boolean;odds:any};
export default function Home(){const[matches,setMatches]=useState<M[]>([]),[league,setLeague]=useState('ALL'),[busy,setBusy]=useState(false),[pred,setPred]=useState<Record<string,any>>({}),[img,setImg]=useState<Record<string,string>>({});
const load=async()=>{try{const j=await fetch('/api/matches',{cache:'no-store'}).then(r=>r.json());setMatches(j.matches||[])}catch{}};useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
const leagues=useMemo(()=>['ALL',...new Set(matches.map(x=>x.league))],[matches]);const shown=league==='ALL'?matches:matches.filter(x=>x.league===league);
async function predict(m:M){setBusy(true);try{const j=await fetch('/api/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({matches:[{id:m.id,home:m.home,away:m.away,league:m.league}]})}).then(r=>r.json());const p=j.predictions?.[0]?.prediction||j.predictions?.[0]||j.prediction;setPred(v=>({...v,[m.id]:p}))}finally{setBusy(false)}}
async function image(m:M){const p=pred[m.id];const j=await fetch('/api/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:`${m.home} vs ${m.away}, ${m.league}, prediction ${p?.result?.pick||'analyse'} confidence ${Math.round((p?.result?.confidence||0)*100)}%`})}).then(r=>r.json());if(j.url)setImg(v=>({...v,[m.id]:j.url}))}
return <main className='shell'><header className='top'><div><div className='brand'>SOLITAIRE HACK 🇨🇮</div><div className='tag'>Il est temps de voir grand</div></div><nav className='nav'><Link href='/'>Matchs</Link><Link href='/coupon'>Coupon IA</Link><Link href='/suivi'>Suivi</Link><Link href='/ia'>IA</Link></nav></header><section className='hero'><div className='tag'>CENTRE DE PRÉDICTIONS</div><h1>Voir le match avant le match.</h1><p className='muted'>Flux réel → moteur de prédiction → suivi automatique. Les probabilités restent des estimations, jamais une garantie.</p></section><div className='controls'><select className='select' value={league} onChange={e=>setLeague(e.target.value)}>{leagues.map(x=><option key={x}>{x}</option>)}</select><button className='btn' onClick={load}>↻ Actualiser</button><span className='tag'>{shown.length} matchs · synchronisation 5s</span></div><div className='grid'>{shown.map(m=><article className='card' key={m.id}><div className='league'>{m.league}</div><div className='teams'><span>{m.home}</span><span className='score'>{m.scoreHome} — {m.scoreAway}</span><span>{m.away}</span></div><div className='row'><span className={'badge '+(m.live?'live':'')}>{m.finished?'TERMINÉ':m.live?'EN DIRECT':'À VENIR'}</span><span className='small'>1 {m.odds?.home??'—'} · X {m.odds?.draw??'—'} · 2 {m.odds?.away??'—'}</span></div>{pred[m.id]?<><div className='row'><strong>{pred[m.id]?.result?.pick||'ANALYSE'}</strong><strong>{Math.round((pred[m.id]?.result?.confidence||0)*100)}%</strong></div><div className='bar'><i style={{width:`${Math.min(100,(pred[m.id]?.result?.confidence||0)*100)}%`}}/></div></>:<div className='muted small'>Aucune prédiction chargée</div>}<div className='controls'><Link className='btn' href={`/match/${encodeURIComponent(m.id)}`}>Détails</Link><button className='btn' disabled={busy} onClick={()=>predict(m)}>⚡ Prédire</button>{pred[m.id]&&<button className='btn' onClick={()=>image(m)}>▣ Image</button>}</div>{img[m.id]&&<img src={img[m.id]} alt='Carte prédiction' style={{width:'100%',borderRadius:14,marginTop:8}}/>}</article>)}</div><footer className='footer'>SOLITAIRE HACK 🇨🇮 · FIFA VIRTUAL / 1XBET / MELBET / MEGAPARI / PREMIERBET · Les données et probabilités sont informatives.</footer></main>}
